name: xcube-server-dev

channels:
  - conda-forge
  - defaults

dependencies:
  - python =3.6*
  #
  # runtime dependencies
  #
  - boto3 =1.9.2
  - botocore =1.12.3
  - cython =0.28.5
  - fiona =1.8b2
  - h5netcdf =0.6.2
  - matplotlib =2.2.3
  - netcdf4 =1.4.0
  - numpy =1.15.1
  - pandas =0.23.4
  - pillow =5.2.0
  - pyyaml =3.13
  - shapely =1.6.4
  - s3fs =0.1.6
  - tornado =5.1
  - xarray =0.10.8
  - zarr =2.2.0
  #
  # development tools
  #
  # development dependencies
  #
  - flake8 =3.5.0
  - pytest =3.8.0
  - pytest-cov =2.6.0
